#开发时用到的配置文件,与项目上线时分割
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: blm_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tPzVJwZY9WoGibnkVso
    access-key-secret: DoK8hQcHwf1GP0djMDGsNekeyxhoZb
    bucket-name: blm-take-out
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxe86d3d3f1d1a15ea
    secret: 1ba9766800bbca789630edafdcb6ed58